Fix: NoClassDefFoundError for UnsynchronizedBufferedReader in CSV import
Added commons-io to base app dependencies to fix ClassNotFoundException when importing CSV files. Dynamic feature modules require transitive dependencies to be declared in the base module, otherwise D8 won't package them in split APKs.